### ISSUE TITLE
testing on vagrant

### ISSUE THREAD

**Issue by thbeh** [basho-labs/vagrant-bdp-cluster#1]
i clone the above but got issue when i run download.sh. Any thoughts?

http://: Invalid host name.
failed to download bdp package for centos

**Comment by mbbroberg** [comment]
Same. I'm checking into this @thbeh. FYI cc @paegun

**Comment by paegun** [comment]
Please see the README.md section regarding setting env.sh. This vagrant setup requires configuring download links and which target environment, ie 'centos'.

**Comment by thbeh** [comment]
i did this - 

TARGET_VM=centos TARGET_VM_COUNT=3 vagrant up

**Comment by thbeh** [comment]
I guess the url is not set at env.sh -

# url for the bdp rpm package for centos

export DOWNLOAD_BDP_PACKAGE_CENTOS_URL=""

# url for the bdp extras tarball for centos

export DOWNLOAD_BDP_EXTRAS_CENTOS_URL=""

**Comment by paegun** [comment]
@thbeh, you are correct, the urls should be set to download the packages required.

**Comment by thbeh** [comment]
so what is the url?

**Comment by mbbroberg** [comment]
Hey @thbeh - that's the detail you needed to know: BDP is not for public download just yet. We're running a private beta at the moment. This Vagrantfile is an excellent way to understand its parts, but it's missing the code that'd make it interesting for you right now :smile: 

Tell you what: shoot me a note (mbrender /at/ basho.com) about why you're interested in digging in and I'll see if I can get you a copy before too long. 

Thanks!
