### ISSUE TITLE
chef vagrant boxes have been removed/moved

### ISSUE THREAD

**Issue by roooms** [basho-labs/vagrant-bdp-cluster#3]
Chef have [removed all boxes](https://atlas.hashicorp.com/chef/) from Atlas and now link to [Bento boxes](https://atlas.hashicorp.com/bento/), which have later versions per release, e.g. centos-6.7 instead of centos-6.5. Not sure if these are compatible with the rest of this project.

**Comment by paegun** [comment]
This is resolved in 8d332fcf5481c6253957681969b3d79e0429ec84 . Thank you.
